### ISSUE TITLE
Whitespace in resulting domain xml

### ISSUE THREAD

**Issue by sebastianrakel** [cirrax/puppet-libvirt#77]
Hi,

i updated my puppet repo to puppet 8 and updated the libvirt module also to version v5.0.4.

Now i have the following problem, i defined some custom profile which sets the emulator value:

```
libvirt::profiles::devices:
  node:
    profileconfig:
      base: "default"
      merge: "merge"
    emulator:
      values: "/usr/bin/qemu-system-x86_64"
```
if i'm using this profile the emulator line in xml will look like this:
`<emulator> /usr/bin/qemu-system-x86_64</emulator>` there is a leading whitespace
which results in: 
error: 

> Cannot check QEMU binary  /usr/bin/qemu-system-x86_64: No such file or directory ...

if i remove the whitespace everything works nicely
